ED-313: reading extra field revertStatus from request
rbkmoney/wapi_v0 pull request #34
Opened 2021-11-09 18:40 UTC by yuri-bukhalenkov

2021-11-10 09:28 UTC, yuri-bukhalenkov commented
> Ожидаю изменений во внутреннем протоколе для проверки :)

Там не нужны изменения:
https://github.com/rbkmoney/fistful-proto/blob/914c9986d45635f93569d896f515a0b3e93ea913/proto/fistful_stat.thrift#L140-L148

https://github.com/rbkmoney/wapi_v0/blob/de8fca96d2a4f5b54fcb7b89a6b8c8e3ef31eef3/apps/wapi/src/wapi_stat_backend.erl#L93-L106

2021-11-10 09:45 UTC, jrogov commented
А результат?
ЕЯПП, сюда нужно поле добавить:
https://github.com/rbkmoney/fistful-proto/blob/914c9986d45635f93569d896f515a0b3e93ea913/proto/fistful_stat.thrift#L71-L81

2021-11-12 08:55 UTC, jrogov requested changes

2021-11-12 08:55 UTC, jrogov commented on apps/wapi/src/wapi_stat_backend.erl
> +    atom_to_binary(Status).
См. https://github.com/rbkmoney/swag-wallets/pull/99#discussion_r745567145
Нужно будет апкейснуть после этого

2021-11-12 11:33 UTC, yak-zuk-zop commented on apps/wapi/src/wapi_stat_backend.erl
> +    atom_to_binary(Status).
Готово

2021-11-15 11:17 UTC, jrogov approved these changes

2021-11-15 11:30 UTC, merged